<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function social_comment_upload_form_comment_comment_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['field_comment_files'])) {
    $form['field_comment_files']['widget']['#file_upload_title'] = '';
    $form['#attached']['library'][] = 'social_comment_upload/comment_upload';
    $form['#after_build'][] = 'social_comment_upload_form_comment_comment_form_after_build';

    $route_name = \Drupal::routeMatch()->getRouteName();

    // The "value" HTML attribute should be equal to the "#value" parameter of an array of the button.
    // @see social_comment_form_comment_form_alter().
    switch ($route_name) {
      case 'comment.reply':
        $form['actions']['submit']['#attributes']['value'] = t('Reply');
        $form['actions']['submit']['#value'] = t('Reply');
        break;

      case 'entity.comment.edit_form':
        $form['actions']['submit']['#attributes']['value'] = t('Submit');
        $form['actions']['submit']['#value'] = t('Submit');
        break;

      default:
        // By default the comment form has the "Reply comment" page URL in the "action" attribute.
        // So we should set the current URL to exclude changing the route name.
        // Otherwise this "switch" will not work.
        $form['#action'] = \Drupal::request()->getRequestUri();
        $form['actions']['submit']['#attributes']['value'] = t('Comment');
        $form['actions']['submit']['#value'] = t('Comment');
        break;
    }
  }
}

/**
 * Removes the select list with "weight" value.
 */
function social_comment_upload_form_comment_comment_form_after_build($form, FormStateInterface $form_state) {
  foreach ($form['field_comment_files']['widget'] as $key => &$element) {
    if (is_array($element) && isset($element['_weight'])) {
      unset($element['_weight']);
    }
  }

  return $form;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function social_comment_upload_preprocess_file_widget_multiple(&$variables) {
  $element = $variables['element'];

  if ($element['#field_name'] == 'field_comment_files') {
    // Remove "weight" column.
    foreach ($variables['table']['#rows'] as $key => $row) {
      if (!empty($element['#display_field'])) {
        unset($variables['table']['#rows'][ $key ]['data'][2]);
      }
      else {
        unset($variables['table']['#rows'][ $key ]['data'][1]);
      }
    }

    // Remove headers and disable sorting rows.
    $variables['table']['#header'] = [];
    $variables['table']['#tabledrag'] = [];
  }
}
